[package]
name = "llm-box"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
ultimate-common = { workspace = true }
tokio = { workspace = true }
dotenvy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
# rig
rig-core = { workspace = true }
rig-postgres = { workspace = true }
