[package]
name = "fusion-grpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
publish = true

[lints.rust]
unsafe_code = "allow"

[features]
default = []

[dependencies]
fusion-common = { workspace = true }
fusion-core = { workspace = true, features = ["tonic"] }
uuid = { workspace = true }
http = { workspace = true }
futures = { workspace = true }
config = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tower-service = { workspace = true }
tower-http = { workspace = true }
tonic = { workspace = true }
tonic-types = { workspace = true }
tonic-web = { workspace = true, optional = true }
tonic-reflection = { workspace = true, optional = true }
protobuf = { workspace = true }
